#####
POST http://localhost:3003/api/blogs 
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRodXZhbjEyMyIsImlkIjoiNjU4NDY1NTU3YzIxNTBlNDZmZTQzMDg1IiwiaWF0IjoxNzAzMTc2OTgyfQ.iCYUrMu27B61bxv9BGzcOX7dQX8nR6pX8VoKyYMYk0g
{
    "title": "test blog", 
    "author": "thanhduong", 
    "url": "www.facebook.com", 
    "likes": 1000
}
######
POST http://localhost:3003/api/users 
Content-Type: application/json

{
    "username": "thanhduongTest",
    "name": "abcd",
    "passwordHash": "abcd123456",
    "notes": []
}

######
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "thanhduongTest",
    "password": "abcd123456"
}

###
POST http://localhost:3003/api/blogs 
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYW5oZHVvbmdUZXN0IiwiaWQiOiI2NTg4NDY0MTEyNjUxYTZmOWJmNTgwZTkiLCJpYXQiOjE3MDM0Mjk3Mjh9.0_uJgMF0PTHXRV3ZJU0a89B-3nwTKuEqcr3BcVZ86ms

{
    "title": "another blog 2", 
    "author": "thanhduong 1", 
    "url": "www.facebook.com", 
    "likes": 1
}
###
DELETE http://localhost:3003/api/blogs/658854264d43809542203508
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoYW5oZHVvbmdUZXN0IiwiaWQiOiI2NTg4NDY0MTEyNjUxYTZmOWJmNTgwZTkiLCJpYXQiOjE3MDM0Mjk3Mjh9.0_uJgMF0PTHXRV3ZJU0a89B-3nwTKuEqcr3BcVZ86ms




#####